### ISSUE TITLE
Image missing in README.md when importing source connector from Helloid.

### ISSUE THREAD

**Issue by patrickhoryn** [Tools4everBV/Tools4everBV-HelloID-Conn-Prov-Source-BambooHR#3]
In the README.md file there is a linked image : "(assets/BambooHRConfiguration.jpg)".
When you use Helloid to import this connector, this image is not seen because Helloid enivrement is different then Github.

So the image link should be : "(https://github.com/Tools4everBV/Tools4everBV-HelloID-Conn-Prov-Source-BambooHR/blob/main/assets/BambooHRConfiguration.jpg)".

**Comment by JeroenBL** [comment]
Fixed in readme.
